#!/bin/bash
 
# --------------------------------------------------------------
### PART 1: Requests resources to run your job.
# --------------------------------------------------------------
#!/bin/bash
#PBS -q standard
#PBS -l select=1:ncpus=21:mem=6gb
#PBS -W group_list=guangyao
#PBS -l place=pack:shared
#PBS -l walltime=00:60:00
# --------------------------------------------------------------
### PART 2: Executes bash commands to run your job
# --------------------------------------------------------------
### Load required modules/libraries if needed
module load java/8/1.8
### change to your script’s directory
cd /home/u15/sateeshp/reach_pubmed
### Run your work
java -cp ./reach-1.6.2-SNAPSHOT-FAT.jar org.clulab.processors.server.ProcessorServer
java -jar reach-1.6.2-SNAPSHOT-FAT.jar
